### ISSUE TITLE
TSC timer calculation causes multiplication overflow in debug mode

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#188]
build and run in debug mode: `make run BUILD_MODE=debug host=yes` 
(use host acceleration, otherwise it takes minutes to boot)

```
[E] PANIC was unhandled in task "terminal_loop" on core Some(0) at panicked at 'attempt to multiply with overflow', kernel/tsc/src/lib.rs:17:13
[D] task_wrapper [1]: "ls-a8f0fd0e094f1b6f" about to call kthread func 0xffffff80072e7990 with arg [], interrupts are true
[E] Killing panicked task "terminal_loop"
```

Should be an easy fix.  Can use u128, or do a different frequency conversion, or use a safer arithmetic operator (wrapping/saturating, whatever makes sense).

**Comment by Narasimha1997** [comment]
Hi, is this issue still open? I can start making a PR if it's still open.

**Comment by kevinaboos** [comment]
> Hi, is this issue still open? I can start making a PR if it's still open.

Hi @Narasimha1997, thanks for your interest! We don't generally use debug mode any more, but this still might be an issue, yes. It's definitely worth looking into this. 

The fix should be simple, such as using a `u128` to represent time and perhaps using a wrapping multiplication operation (as suggested above). We're happy to accept PRs from anyone. 👍

**Comment by Narasimha1997** [comment]
@kevinaboos check out #441

**Comment by kevinaboos** [comment]
thanks! I left a comment there.
