### ISSUE TITLE
"Published academic papers" hyper link in read me is broken

### ISSUE THREAD

**Issue by w62** [theseus-os/Theseus#406]
The link https://github.com/theseus-os/Theseus/blob/theseus_main/book/src/papers_presentations.md is broken.

**Comment by w62** [comment]
I have found [it](https://theseus-os.github.io/Theseus/book/misc/papers_presentations.html).

**Comment by kevinaboos** [comment]
Hi @w62, thanks for the report! I'm glad you found the right link, but can you let me know where you found that dead link initially? I'd like to fix it for others in the future.

**Comment by kevinaboos** [comment]
Thanks, I found the links in the README. Appreciate you finding the dead links!

**Comment by w62** [comment]
> Hi @w62, thanks for the report! I'm glad you found the right link, but can you let me know where you found that dead link initially? I'd like to fix it for others in the future.

Hi Kevin, 

I just click follow book style documentation, then click Papers and Presentations/Slides at the very bottom.

william

**Comment by kevinaboos** [comment]
Thanks, can you try it again now? Everything should be fixed.

**Comment by w62** [comment]
> Thanks, can you try it again now? Everything should be fixed.

Yes, it is working fine now. Thanks for resolving the issue.

**Comment by kevinaboos** [comment]
Great! Thanks again for bringing it to our attention.
