### ISSUE TITLE
Question: How does TheseusOS advoid state spill if a server MUST know some information about a client?

### ISSUE THREAD

**Issue by ali-fire-dev** [theseus-os/Theseus#413]
TheseusOS seems great !  May I have a question?

We know that state spill occurs in Android’s ClipboardService and AlarmManagerService, which may  cause user applications not to work  properly when these service restart after a crash. For example, when ClipboardService restarts, it loses previous data such as some copied texts, and causes the client unable  to paste. 

I wonder that how TheseusOS solves this problem if the service (similar to ClipboardService) in TheseusOS doesn't hold any information (such as the copied texts to paste) about the client. 
If a ClipboardService doesn't hold any texts from client, how can it works?

Thank you for your reply！

**Comment by kevinaboos** [comment]
Hi @ali-fire-dev, thanks for the question! Recently we've moved away from a focus on state spill, but I'm happy to answer this question.

For this specific type of spill, there's no clean/easy way to avoid it. There are some implementation tricks we can leverage, such as externalizing server-side state such that a crashed service could restore its checkpointed state upon restart, or using server-side weak references to client-owned state such that the server doesn't actually own any state. In general, some forms of spill are unavoidable (especially if you wish to enable certain kinds of functionality), so here it'd be more about avoiding/mitigating the adverse effects of state spill with one of the aforementioned implementation tricks.

**Comment by ali-fire-dev** [comment]
> Hi @ali-fire-dev, thanks for the question! Recently we've moved away from a focus on state spill, but I'm happy to answer this question.
> 
> For this specific type of spill, there's no clean/easy way to avoid it. There are some implementation tricks we can leverage, such as externalizing server-side state such that a crashed service could restore its checkpointed state upon restart, or using server-side weak references to client-owned state such that the server doesn't actually own any state. In general, some forms of spill are unavoidable (especially if you wish to enable certain kinds of functionality), so here it'd be more about avoiding/mitigating the adverse effects of state spill with one of the aforementioned implementation tricks.

I see. Thank you for your reply!
