### ISSUE TITLE
Frame allocator will allocate two copies of a frame

### ISSUE THREAD

**Issue by Ramla-I** [theseus-os/Theseus#451]
```
// Allocate pages for RQ and SQ
let (rq_mp, rq_pa) = create_contiguous_mapping(rq_size_in_bytes, NIC_MAPPING_FLAGS)?;
let sq_pa = PhysicalAddress::new(rq_pa.value() + rq_size_in_bytes).ok_or("Could not create starting address for SQ")?; 
let sq_mp = allocate_memory(sq_pa, sq_size_in_bytes)?;
        
// Allocate page for SQ/RQ doorbell
let (db_page, db_pa) = create_contiguous_mapping(4096, NIC_MAPPING_FLAGS)?;
```
This is the portion of code where the problem occurs. The resulting physical address values are:
rq_pa = 0x586b000
sq_pa = 0x587b000
db_pa = 0x587b000

I've traced the issue to the `allocate_frames_deferred()` function in the frame_allocator crate. It seems that when a physical address is provided to the function, it'll add the required frames to the FREE_RESERVED_FRAMES_LIST without checking if that frame is present in the FREE_FRAMES_LIST.

I'm not sure if the solution is to return an Error if a user requests a physical address that is not in the reserved portions, or to return AllocatedFrames from the FREE_FRAMES_LIST.

**Comment by kevinaboos** [comment]
Thanks for filing the issue, I'll look into this immediately.

**Comment by kevinaboos** [comment]
For clarity, the solution was to take the range of requested frames from the general-purpose list of free frames and then treat those frames as reserved from then on.

**Comment by Ramla-I** [comment]
You can still allocate duplicate frames at any given physical address that have been allocated before from the FREE_FRAMES_LIST. That's because the check inserted just ensures that the frames are **currently** not in the free list.

```
let (mp, pa) = create_contiguous_mapping(100, NIC_MAPPING_FLAGS).unwrap();
let mp2 = allocate_memory(pa, 100).unwrap();
let mp3 = allocate_memory(pa, 100).unwrap();
```

mp and mp2 will be allocated with duplicate frames. mp3 will fail because by then we've added that frame to the list of reserved regions.

**Comment by kevinaboos** [comment]
Thanks for correctly identifying this problem! I'll fix it hopefully by tomorrow.
