### ISSUE TITLE
`make`-level parallelism causes a build failure

### ISSUE THREAD

**Issue by jkugelman** [theseus-os/Theseus#531]
I'm running through the build instructions on WSL2 for the first time and am getting a make error:

```
❯ make
make: *** No rule to make target '/home/jkugelman/Theseus/target/x86_64-theseus/release/libnano_core.a', needed by '/home/jkugelman/Theseus/build/nano_core/nano_core-x86_64.bin'.  Stop.
make: *** Waiting for unfinished jobs....
info: component 'rust-src' is up to date
```

**Comment by jkugelman** [comment]
Here's the output from `make -d`:

[make.txt](https://github.com/theseus-os/Theseus/files/8895167/make.txt)

**Comment by jkugelman** [comment]
I have `MAKEFLAGS=-j8` in my environment, which enables parallel make with up to 8 jobs. I turned that off and `make` succeeded.

**Comment by kevinaboos** [comment]
Thanks for the report. Build parallelism is handled in large part by `cargo`, but apparently we haven't properly set up the inter-target dependencies in the `Makefile`. Oops!

**Comment by kevinaboos** [comment]
A good temporary fix for this is to set the built-in `.NOTPARALLEL` option in the `Makefile`.

**Comment by kevinaboos** [comment]
A future PR could experiment with _order-only_ prerequisites: https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types

But we certainly don't need to bother with that now.
