### ISSUE TITLE
Load multiple versions of a crate until a missing symbol is found

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#537]
## Background -- The Problem

Currently, when an unknown/missing symbol is encountered when dynamically linking crates, the crate management system attempts to load the crate containing that missing symbol. It does this recursively as part of the crate loading process. The key function is here: https://github.com/theseus-os/Theseus/blob/13406ed975d54b5d72afb313df370d0a4477ce01/kernel/mod_mgmt/src/lib.rs#L2128

Basically, this works by looking at the missing symbol's demangled name to capture its crate prefix(es). For example, here are some symbols and the crate(s) they may be contained in:
* `<*const T as core::fmt::Debug>::fmt` ->  in `core`
* `<alloc::boxed::Box<T>>::into_unique` -> in `alloc`
* `<framebuffer::VirtualFramebuffer as display::Display>::fill_rectangle` -> in `framebuffer` or `display`
* `keyboard::init` -> in `keyboard`
This is determined by the [`get_containing_crate_name()`](https://github.com/theseus-os/Theseus/blob/7f10a6e5f87efafe07ec78b74bbbf10aa38c67b4/kernel/crate_name_utils/src/lib.rs#L77) function.

When trying to find the crate object file corresponding to that crate prefix, [the code here](https://github.com/theseus-os/Theseus/blob/13406ed975d54b5d72afb313df370d0a4477ce01/kernel/mod_mgmt/src/lib.rs#L2144) assumes that there can only be a single matching crate. However, **this is not necessarily true**, as there could be _multiple_ versions of that same crate that simultaneously exist in the Theseus workspace build. For example, third-party dependencies are likely to exist in many different versions.

## Temporary workaround

Note: currently we've been able to get around this deficiency by manually forcing all dependencies on a given crate across the entire workspace to use the same version of that crate. 
* Example 1: 79900000edefb81537b06ff6f760e5cbb1e31702
* Example 2: 9ae63957d62737d746da9ad258a083de4b8e1f19

However, this isn't scalable or future-proof, as there will eventually be a scenario where cargo cannot resolve multiple requests for different versions of a crate (ones that aren't semver-compatible) into a single dependency.

## The Solution

The `load_crate_for_missing_symbol()` function should handle _multiple_ crate object files that match a given crate prefix, in addition to it handling multiple different crate prefixes for a given symbol.
This can be accomplished perhaps by using [`get_crate_object_files_starting_with(prefix)`](https://github.com/theseus-os/Theseus/blob/13406ed975d54b5d72afb313df370d0a4477ce01/kernel/mod_mgmt/src/lib.rs#L689) within `load_crate_for_missing_symbol()`.

**Comment by NathanRoyer** [comment]
Is there a specified crate version along the symbol name in the relocation table? If we had the crate version, it would be as easy as it is now (and more correct) to locate the symbol (I guess it would look like shared objects in `/usr/lib` in linux: `my-dependency.so.3.4.2`).

**Comment by kevinaboos** [comment]
> Is there a specified crate version along the symbol name in the relocation table? If we had the crate version, it would be as easy as it is now (and more correct) to locate the symbol (I guess it would look like shared objects in `/usr/lib` in linux: `my-dependency.so.3.4.2`).

no, but symbols and crates are implicitly versioned by metadata "hashes" appended to the end of their strings. 

I have briefly considered how we might devise a better way to know which dependencies a various crate has (on foreign symbols) when attempting to link it in. However, I haven't spent enough time on it yet to land on a good solution. One starting point could be the `.d` files generated during compilation, but we'd need to do a fair bit of custom dependency analysis in order to augment those with the specific crate "version" hashes that we'd need.
