### ISSUE TITLE
Improve mutex performance

### ISSUE THREAD

**Issue by tsoutsman** [theseus-os/Theseus#577]
#576 provides a simple mutex implementation; ideally, we'd use a more performant one. Currently, `raw_mutex` only has a fast path (mutex is unlocked) and a slow path (mutex is locked - block current task). We should also have a middle path, which spins for a bit, hoping the mutex is unlocked soon.

Some useful links:
- How Linux does it: https://0xax.gitbooks.io/linux-insides/content/SyncPrim/linux-sync-4.html
- Another possible implementation: https://arxiv.org/pdf/1906.00490.pdf
- The concept of a backoff could be useful in some capacity: https://docs.rs/crossbeam/latest/crossbeam/utils/struct.Backoff.html

**Comment by amab8901** [comment]
#576 isn't merged. How can it the provide the simple mutex implementation? Is this issue still relevant?

**Comment by kevinaboos** [comment]
@tsoutsman now that we have your new sync primitives, do you want to attempt adding the middle path? or just close this issue?
