### ISSUE TITLE
`rand_chacha` crate fails to build on debug mode

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#654]
The `random` crate depends on `rand_chacha`, which apparently fails to build correctly in debug mode.

## Steps to reproduce
```
make run BUILD_MODE=debug
```
You'll see an LLVM error about split operands. 

Note that this doesn't happen in regular release builds, which is odd.

## Related
I fixed a similar LLVM error in the `crc32fast` crate here: https://github.com/srijs/rust-crc32fast/pull/22, which makes me think that this is related to how `rand_chacha` specific its cfg gates for enabling SSE instructions.

**Comment by tsoutsman** [comment]
cc rust-random/rand#1260 cryptocorrosion/cryptocorrosion#69

**Comment by kevinaboos** [comment]
Thanks @tsoutsman, the follow-up issues look good. Appreciate you digging into that!
