### ISSUE TITLE
`async_channel` marks itself as disconnected too eagerly

### ISSUE THREAD

**Issue by kevinaboos** [theseus-os/Theseus#703]
Looks like this was added in #277 (during a paper deadline crunch) so the author was likely only testing it with a single endpoint of each variety. 

Should be a simple enough fix: only mark the channel as disconnected when the _last_ Sender or Receiver gets dropped, not just any sender or receiver.

_Originally posted by @kevinaboos in https://github.com/theseus-os/Theseus/pull/668#discussion_r1031940127_

**Comment by amab8901** [comment]
I think I solved it. Check out my PR and let me know what you think :smile:

**Comment by kevinaboos** [comment]
> I think I solved it. Check out my PR and let me know what you think smile

Thanks! I have left a review on #707.
