### ISSUE TITLE
Add a clippy Make target

### ISSUE THREAD

**Issue by tsoutsman** [theseus-os/Theseus#743]
The logic from the clippy workflow should be moved into a `clippy` target in the Makefile. The workflow should then invoke the target.

This would allow for easier local testing.

**Comment by kevinaboos** [comment]
Agreed. I can just finish off the remaining clippy tasks and then we can ditch the whole `lints.txt` file (cc #526) which would make the clippy invocation even simpler

**Comment by amab8901** [comment]
clippy currently gives a gigantic list of warnings. I'm thinking of fixing those warnings. Are they applicable in this project, or is it non-applicable due to the nature of the project?
