### ISSUE TITLE
Allow access to current page table in `page_table::with`

### ISSUE THREAD

**Issue by tsoutsman** [theseus-os/Theseus#752]
As #747 :airplane: is merged in, I'd like to rework `page_table::with` to allow access to the current page table.

The PR stores the stack/boot info mappings in an array and then iterates over the stored mappings in the `page_table::with` function. We do this because, for the duration of the function, the recursive index points to the new page table and hence the current page table is inaccessible. However, it isn't technically necessary, as the mappings are still in the physical memory.

I [made an attempt](https://github.com/tsoutsman/Theseus/commit/1cb3d5084f319edfec3ed2c1dd90affd8af5a29c), but quickly realised it's trickier than it seems. My idea was to create a `PageTable<Active>` and `PageTable<Inactive>`. An inactive page table would store its temporary mapping, whereas an active page table would use the recursive address. However, this doesn't work because an inactive page table must also map the L3, L2, and L1 tables when accessing them.

An easier middle ground between the current hack and full access to the current page table would be to only map the L1 tables containing the stack/boot info mappings and iterate over them when modifying the new page table.

**Comment by amab8901** [comment]
Have you considered doing just L1 and L2 (without L3) and fully completing every aspect of it, before adding L3 later on?
