### ISSUE TITLE
Add documentation/comments to infinite loops

### ISSUE THREAD

**Issue by amab8901** [theseus-os/Theseus#808]
After https://github.com/theseus-os/Theseus/pull/806 has been merged, go through every empty loop (marked by `#[allow(clippy::empty_loop)]`) and add explanation for why the empty loop is necessary and criteria for replacing it with something else.

Each empty loop should have its own independent explanation case-by-case (rather than having a single explanation that covers multiple empty loops, or copy+pasting boilerplate). Because that extra scrutiny might reveal an (otherwise hard to spot) opportunity for improvement to future system developers. 

@kevinaboos

**Comment by kevinaboos** [comment]
Thanks for filing this!
