### ISSUE TITLE
Add tests for `async_channel`

### ISSUE THREAD

**Issue by amab8901** [theseus-os/Theseus#916]
(follow-up on https://github.com/theseus-os/Theseus/pull/837)

This addresses the last check on: https://github.com/theseus-os/Theseus/issues/715

The following scenarios should be tested:
 - [ ] the clone method on Sender/Receiver
 - [ ] dropping a Sender or Receiver when multiple ones exist already, rather than just a single one.
 - [ ] Trying to send to or receive from a disconnected channel
 - [ ] Whether the Receiver::sender() and Sender::receiver() methods properly change the Channel's state in the case of multiple endpoints or a single endpoint.
 - [ ] Actually recovering from a channel disconnection using the above methods and then successfully sending and/or receiving through the channel
 - [ ] Anything with more than two tasks -- a common use case would be to have several sending tasks and several receiving tasks, so we want to test whether that works properly.

But first, I think we need to identify every scenario that should be tested, so that we aren't missing anything

**Comment by kevinaboos** [comment]
Logistics comment: rather than opening up duplicate issues, can you merge them into one? Might as well add these checkbox bullet points to #715.
