### ISSUE TITLE
`test_channel` bug (deadlock?)

### ISSUE THREAD

**Issue by amab8901** [theseus-os/Theseus#924]
Steps to reproduce:
1) use `theseus_main` branch
2) `make full orun`
3) in Theseus: 
```
cd namespaces/_applications
test_channel -ao
test_channel -ao
```
If you run the 2nd `test_channel -ao` while the first one is still running, then the OS gets stuck. I suspect this to be a deadlock. And the message says that the first `test_channel -ao` is finished before it actually is (i.e. if you run the 2nd one immediately after receiving the "finished" message, then you will get stuck by what appears to be a deadlock).

# Generalization:
This bug doesn't occur for:
* `test_channel -am`
* `test_channel -rm`

Similar bug (i.e. similar way to reproduce it but not necessarily same nature of bug) also occurs for:
* `test_channel -ro`

# Update: 
It seems like the bug originates from `Taskbuilder::spawn()`.

**Comment by kevinaboos** [comment]
this has been resolved with recent commits. Thanks for the report!
